authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = dev.erp.hansacore.com
DNS.2 = dev.hansacore.com
DNS.3 = dev.auth.hansacore.com
DNS.4 = k3s-lab.mshome.net
DNS.5 = localhost
IP.1 = 127.0.0.1
IP.2 = 172.23.13.159
