authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
IP.1 = 172.19.148.154
IP.2 = 172.19.148.154
IP.3 = 172.22.132.198
IP.4 = 127.0.0.1
DNS.1 = localhost
DNS.2 = k3s-lab.mshome.net
DNS.3 = hansacore.local
DNS.4 = *.mshome.net
