apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hansacore-tls
  namespace: hansacore
spec:
  secretName: hansacore-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - uat.hansacore.com
    - uat.erp.hansacore.com
    - uat.auth.hansacore.com
